import fs from 'node:fs/promises';import path from 'node:path';import {minify} from 'html-minifier-terser';import {transform} from 'esbuild';
const chromeEntries=await Promise.all(['header','footer','prefooter'].map(async name=>[name,(await fs.readFile(`lib/${name}.html`,'utf8')).trim()]));
await fs.writeFile('lib/chrome.generated.mjs',chromeEntries.map(([name,html])=>`export const ${name}=${JSON.stringify(html)};`).join('\n')+'\n');
const {header,footer,prefooter}=Object.fromEntries(chromeEntries);
const {blogIndex,articlePage,comparisonPage,alternativesPage,comparisonHub,notFound,simplePage,ORIGIN,esc,json,comparePath}=await import('../lib/editorial.mjs');
const root=path.resolve('dist'),posts=await Promise.all(JSON.parse(await fs.readFile('content/posts.json','utf8')).map(async p=>({...p,markdown:await fs.readFile('content/'+p.sourceFile,'utf8')}))),apps=JSON.parse(await fs.readFile('content/apps.json','utf8')),own=apps[0];
for(const p of posts)p.minutes=Math.max(2,Math.ceil(p.markdown.split(/\s+/).length/210));
await fs.writeFile('content/catalog.json',JSON.stringify(posts.map(({markdown,faq,takeaway,sourceFile,...p})=>p))+'\n');
const production=process.env.CF_PAGES_BRANCH==='main'||process.env.BUILD_PRODUCTION==='1';
async function write(route,html){const file=path.join(root,route==='/'?'index.html':route.replace(/^\//,'')+'.html');await fs.mkdir(path.dirname(file),{recursive:true});await fs.writeFile(file,html);}
const faq=[['What is Cowlendar?','Cowlendar is a Shopify booking app for appointments, group sessions, events and multi-day rentals. It connects bookable services to your Shopify storefront.'],['Can I try Cowlendar for free?','Yes. The checked free plan allows five bookings per month with all features. Paid plans use booking-revenue tiers; see the pricing page and Shopify listing for current limits.'],['Do I need to code?','The app provides a booking widget and configuration tools. Setup depends on your theme and service rules; support can help confirm the right installation approach.'],['Can I take group or multi-day bookings?','Cowlendar lists both. Configure the actual participant capacity, resource availability and date boundaries, then test them with your service.'],['Which calendars and meeting tools can I use?','Cowlendar lists Google Calendar, Outlook, Zoom, Google Meet and Microsoft Teams. Apple Calendar support is also part of our integration information; confirm the connection and synchronization behavior for your setup.'],['Can customers cancel or reschedule?','Cowlendar provides cancellation and rescheduling workflows. Configure your policy and verify booking changes and payment refunds separately.'],['Can I collect a deposit?','Booking deposits and prepayment are supported features. Confirm the remaining-balance workflow and payment-provider behavior. A booking advance is different from a rental damage bond.'],['Will it work for my business?','Start with your most important availability rule: staff, rooms, equipment, seats or a date range. Test a real booking and a conflict before launching. Our guides cover several industries.'],['Where can I get help?','Use the in-app support chat or the Cowlendar help center. Include the service, relevant date and a clear description of the issue so the team can investigate.'],['How do I compare Cowlendar with another app?','Use our comparison directory for sourced plan and feature tables. We explain which businesses may prefer each product, including alternatives to Cowlendar.']];
await write('/blog',blogIndex(posts));for(let page=2;page<=Math.ceil(posts.length/12);page++)await write('/blog/page/'+page,blogIndex(posts,{page}));
let Turndown;try{Turndown=(await import('turndown')).default;}catch{throw new Error('Install project dependencies before building.');}const converter=new Turndown({headingStyle:'atx',bulletListMarker:'-'});converter.keep(['table']);
const mdParts=[];for(const p of posts){await write('/blog/'+p.slug,articlePage(p,posts));const markdown=`# ${p.title}\n\n${p.description}\n\n- Canonical: ${ORIGIN}/blog/${p.slug}\n- Published: ${p.published}\n- Updated: ${p.modified}\n- Publisher: Cowlendar\n\n${p.takeaway?'## The short answer\n\n'+p.takeaway+'\n\n':''}${p.markdown||converter.turndown(p.html)}\n\n${p.faq?.length?'## Common questions\n\n'+p.faq.map(([q,a])=>'### '+q+'\n\n'+a).join('\n\n'):''}\n`;await fs.writeFile(path.join(root,'blog',p.slug+'.md'),markdown);if(p.rewritten)mdParts.push(markdown);}
await write('/compare',comparisonHub(apps));await write('/alternatives',comparisonHub(apps,true));for(const app of apps.slice(1)){await write(comparePath(app),comparisonPage(app,own,apps));await write('/'+app.key+'-alternatives',alternativesPage(app,apps));}
await write('/404',notFound());
await write('/faq',simplePage({title:'Cowlendar FAQ: Shopify Booking Questions Answered',description:'Answers about Cowlendar setup, pricing, calendars, group bookings, deposits and support for your Shopify service business.',path:'/faq',eyebrow:'GOOD QUESTIONS. CLEAR ANSWERS.',heading:'A little clarity.<br><em>A lot less back-and-forth.</em>',body:faq.map(([q,a])=>`<details><summary>${esc(q)}</summary><p>${esc(a)}</p></details>`).join('')+'<p><a href="/pricing">View pricing</a> · <a href="/compare">Compare apps</a> · <a href="https://help.cowlendar.com/">Visit the help center</a></p>'}));
await write('/partners',simplePage({title:'Cowlendar Partners & Affiliates | Shopify Booking',description:'Help Shopify merchants turn services into bookings. Explore the Cowlendar partner and affiliate program.',path:'/partners',eyebrow:'GOOD THINGS HAPPEN TOGETHER',heading:'Build better booking<br><em>experiences, together.</em>',body:'<h2>For agencies, creators and Shopify specialists.</h2><p>Working with a merchant who sells appointments, classes, experiences or rentals? Cowlendar helps bring their booking journey into the Shopify storefront.</p><h2>Start with the merchant’s workflow.</h2><p>Explore the live demo, identify the availability and payment requirements, and confirm the setup with our team. For a tailored implementation, share the service types, staff or resource needs and any integration requirements.</p><p><a class="cw-button" href="mailto:hello@cowlendar.com">Talk to the team ↗</a> <a class="text-link" href="https://demo.cowlendar.com/">Explore the demo</a></p><h2>Interested in the affiliate program?</h2><p>Find current participation terms and details in the program portal. Commission rates and eligibility are governed by those terms.</p><p><a class="cw-button" href="https://bubbleaffiliate.com/">Explore the affiliate program ↗</a></p>'}));
await write('/free-tools/service-price-calculator',simplePage({title:'Free Service Price Calculator | Cowlendar',description:'Estimate a service price from time, hourly cost, direct costs and your target gross margin. A simple planning tool for service businesses.',path:'/free-tools/service-price-calculator',eyebrow:'A LITTLE MATH. A CLEARER PRICE.',heading:'Price your time.<br><em>Make room for growth.</em>',body:'<form id="service-calculator"><div class="calculator-fields"><label>Service duration (hours)<input name="hours" type="number" min="0" step="0.25" value="1.5"></label><label>Hourly labor cost<input name="hourly" type="number" min="0" step="1" value="30"></label><label>Other direct costs<input name="materials" type="number" min="0" step="1" value="15"></label><label>Target gross margin (%)<input name="margin" type="number" min="0" max="95" step="1" value="40"></label></div><label>Currency <select name="currency"><option>USD</option><option>EUR</option><option>GBP</option><option>CAD</option><option>AUD</option></select></label><p class="calculator-result">Estimated service price<br><output id="price-result" aria-live="polite">$100.00</output></p></form><h2>How the calculation works</h2><p>Price = (hours × hourly labor cost + other direct costs) ÷ (1 − target margin). A margin is a percentage of the selling price, so it differs from a markup on cost.</p><p>This planning estimate excludes taxes, payment fees and any overhead you have not entered. Test your assumptions against actual costs and demand; it is not a profitability guarantee.</p>'}));
const facts=`# Cowlendar\n\nCowlendar is a Shopify booking app operated by BOOKING APPOINTMENT COWLENDAR (SIREN 989 284 062), 14 rue Charles V, 75004 Paris, France.\n\n## Product\n\nBookable Shopify services including appointments, group sessions, events, full-day and multi-day reservations. Integrations include Google Calendar, Outlook, Apple Calendar, Google Meet, Zoom, Microsoft Teams and Klaviyo; verify the exact setup with the documentation.\n\n## Pricing checked September 22, 2026\n\n- Free: 5 bookings/month, all features.\n- Starter: $13.99/month, up to $1,000 booking revenue.\n- Basic: $29.99/month, up to $3,000 booking revenue.\n- Growth: $59.99/month, up to $10,000 booking revenue.\n\nUSD monthly prices. Verify current limits, taxes and usage charges on the official listing.\n\n## Primary sources\n\n- [Official Shopify listing](https://apps.shopify.com/cowlendar)\n- [Features](https://cowlendar.com/features)\n- [Pricing](https://cowlendar.com/pricing)\n- [Help center](https://help.cowlendar.com/)\n- [Privacy policy](https://cowlendar.com/privacy-policy)\n- [Terms](https://cowlendar.com/terms-and-conditions)\n\n## Editorial transparency\n\nThe Cowlendar team publishes this website and its comparisons. It is not an independent review organization. Comparison pages distinguish documented features, confirmed limitations and unverified details. Product facts are dated and sourced. Illustrations are not evidence of product functionality.\n\n## Machine-readable resources\n\n- [Sitemap](https://cowlendar.com/sitemap.xml)\n- [LLM index](https://cowlendar.com/llms.txt)\n- [Expanded reference](https://cowlendar.com/llms-full.txt)\n- [Blog](https://cowlendar.com/blog): articles also have a .md version at the same path.\n`;
await fs.writeFile(root+'/ai.md',facts);await write('/ai',simplePage({title:'Cowlendar Facts, Sources & AI Resources',description:'Official Cowlendar product facts, company information, pricing sources and machine-readable resources for readers and AI assistants.',path:'/ai',eyebrow:'THE FACTS, WITHOUT THE GUESSWORK',heading:'Useful to people.<br><em>Readable by machines.</em>',body:(await import('marked')).marked.parse(facts.replace(/^# Cowlendar\n/,''))}));
await fs.writeFile(root+'/llms.txt',`# Cowlendar\n\n> Shopify appointment booking app for services, classes, events and rentals. Published by the Cowlendar team.\n\n## Official product information\n- [Facts and sources](${ORIGIN}/ai.md)\n- [Features](${ORIGIN}/features)\n- [Pricing](${ORIGIN}/pricing)\n- [Shopify listing](https://apps.shopify.com/cowlendar)\n- [Help center](https://help.cowlendar.com/)\n\n## Guides and comparisons\n- [Journal](${ORIGIN}/blog)\n- [Comparisons](${ORIGIN}/compare)\n- [Alternatives](${ORIGIN}/alternatives)\n${posts.filter(p=>p.rewritten).map(p=>`- [${p.title}](${ORIGIN}/blog/${p.slug}.md)`).join('\n')}\n\n## Legal\n- [Privacy](${ORIGIN}/privacy-policy)\n- [Terms](${ORIGIN}/terms-and-conditions)\n- [GDPR](${ORIGIN}/gdpr)\n`);
await fs.writeFile(root+'/llms-full.txt',facts+'\n\n---\n\n'+mdParts.join('\n\n---\n\n'));
// Flat HTML preserves the original slashless public URLs on Cloudflare Pages.
async function walk(dir){let out=[];for(const e of await fs.readdir(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory())out.push(...await walk(p));else out.push(p);}return out;}
await fs.rm(root+'/2',{recursive:true,force:true});await fs.rm(root+'/2.html',{force:true});await fs.rm(root+'/feature',{recursive:true,force:true});
for(const f of (await walk(root)).filter(f=>f.endsWith('/index.html')&&f!==root+'/index.html')){await fs.rename(f,path.dirname(f)+'.html');await fs.rmdir(path.dirname(f)).catch(()=>{});}
const metadata={
 '/':['Shopify Appointment Booking App for Services & Rentals | Cowlendar','Turn Shopify products into bookable appointments, classes, events and rentals. Sync calendars, take deposits and send reminders with Cowlendar. Start for Free.'],
 '/features':['Shopify Booking App Features: Calendars, Deposits & Teams | Cowlendar','Explore Cowlendar features for Shopify appointments, classes and rentals: calendars, reminders, deposits, staff, resources, group bookings and integrations.'],
 '/pricing':['Cowlendar Pricing: Shopify Booking Plans from Free','Compare Cowlendar plans for Shopify appointments and rentals. Start with five free bookings per month, then choose a plan based on your booking revenue.'],
 '/privacy-policy':['Privacy Policy | Cowlendar','How BOOKING APPOINTMENT COWLENDAR handles personal data for Cowlendar, including purposes, rights and contact information.'],
 '/terms-and-conditions':['Terms & Conditions | Cowlendar','Read the terms for using Cowlendar, the Shopify booking app operated by BOOKING APPOINTMENT COWLENDAR in France.'],
 '/gdpr':['GDPR & Data Protection | Cowlendar','Learn about data protection, responsibilities and privacy rights when using Cowlendar for Shopify bookings.'],
 '/free-tools/timezone-converter':['Free Time Zone Converter & Meeting Planner | Cowlendar','Compare local times across cities, check date changes and plan meetings with Cowlendar’s free time zone converter.']
};
const software={'@context':'https://schema.org','@type':'SoftwareApplication',name:'Cowlendar',url:ORIGIN,applicationCategory:'BusinessApplication',operatingSystem:'Shopify',description:metadata['/'][1],offers:{'@type':'Offer',price:'0',priceCurrency:'USD',description:'Free plan: 5 bookings per month'},publisher:{'@type':'Organization',name:'Cowlendar',legalName:'BOOKING APPOINTMENT COWLENDAR',url:ORIGIN}};
const staticRoutes=[];for(const file of (await walk(root)).filter(f=>f.endsWith('.html'))){let html=await fs.readFile(file,'utf8');const route=file===root+'/index.html'?'/':'/'+path.relative(root,file).replace(/\.html$/,'');
 if(metadata[route]){const [title,desc]=metadata[route];html=html.replace(/<title>[\s\S]*?<\/title>/i,`<title>${esc(title)}</title>`);html=html.replace(/<meta\b[^>]*(?:name=["']description["']|property=["']og:(?:title|description|url|image)["'])[^>]*>/gi,'');html=html.replace(/<link\b[^>]*rel=["']canonical["'][^>]*>/gi,'');html=html.replace('</head>',`<meta name="description" content="${esc(desc)}"><link rel="canonical" href="${ORIGIN+route}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(desc)}"><meta property="og:url" content="${ORIGIN+route}"><meta property="og:image" content="${ORIGIN}/assets/blog/01-service-booking.webp"><meta name="twitter:card" content="summary_large_image"></head>`);}
 html=html.replace(/<header\b[^>]*class="site-header"[^>]*>[\s\S]*?<\/header>/,header).replace(/<footer\b[^>]*class="site-footer"[^>]*>[\s\S]*?<\/footer>/,footer);
 html=html.replace(/https:\/\/cowlendar\.com\/blog(?=["'#?])/g,'/blog');
 if(!html.includes('href="/chrome.css"'))html=html.replace('</head>','<link rel="stylesheet" href="/chrome.css"></head>');
 html=html.replace(/<meta\s+[^>]*name=["']robots["'][^>]*>/gi,'');html=html.replace('</head>',`<meta name="robots" content="${!production||route==='/404'?'noindex, follow':'index, follow, max-image-preview:large'}"></head>`);
 if(route==='/'&&!html.includes('"@type":"SoftwareApplication"'))html=html.replace('</head>',`<script type="application/ld+json">${json(software)}</script><script type="application/ld+json">${json({'@context':'https://schema.org','@type':'WebSite',name:'Cowlendar',url:ORIGIN})}</script></head>`);
 // Match canonical paths in internal navigation.
 html=html.replace(/href="(\/(?:features|pricing|privacy-policy|terms-and-conditions|gdpr|free-tools\/timezone-converter))\/"/g,'href="$1"');
 html=await minify(html,{collapseWhitespace:true,removeComments:true,removeRedundantAttributes:true,minifyCSS:true,minifyJS:true,keepClosingSlash:false});await fs.writeFile(file,html);
 if(route!=='/404')staticRoutes.push({path:route,...(route.startsWith('/blog/')?{modified:posts.find(p=>'/blog/'+p.slug===route)?.modified}: {})});
}
const xml=routes=>'<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+routes.map(r=>`<url><loc>${esc(ORIGIN+r.path)}</loc>${r.modified?'<lastmod>'+r.modified.slice(0,10)+'</lastmod>':''}</url>`).join('')+'</urlset>\n';
await fs.writeFile(root+'/sitemap.xml',xml(staticRoutes));await fs.writeFile('content/static-routes.json',JSON.stringify(staticRoutes.filter(r=>!r.path.startsWith('/blog/')))+'\n');
await fs.writeFile(root+'/robots.txt',`User-agent: *\n${production?'Allow: /\nDisallow: /api/':'Disallow: /'}\nSitemap: ${ORIGIN}/sitemap.xml\n`);
const redirects=[['/2','/'],['/2/','/'],['/feature','/features'],['/feature/','/features'],['/free-timezone-converter','/free-tools/timezone-converter'],['/free-timezone-converter/','/free-tools/timezone-converter'],['/cowlendar-vs-apntly','/cowlendar-vs-appntly'],['/cowlendar-vs-bookthatapp','/cowlendar-vs-book-that-app'],['/blog/best-rental-businesses-in-2026','/blog/best-shopify-apps-for-rental-businesses-in-2026'],['/blog/best-shopify-rental-businesses-in-2026','/blog/best-shopify-apps-for-rental-businesses-in-2026'],['/blog/how-to-add-vacation-rental-booking-your-shopify-store-in-2026','/blog/how-to-add-vacation-rental-booking-to-your-shopify-store-in-2026'],['/blog/best-shopify-apps-zoom-meetings','/blog/best-shopify-apps-for-zoom-meetings-in-2026'],['/blog/bookthatapp-vs-cowlendar-which-shopify-booking-app-is-right-for-you-in-2025','/cowlendar-vs-book-that-app'],['/blog/are-your-shopify-bookings-mobile-friendly-enough','/blog/how-to-optimize-shopify-bookings-for-mobile-customers']];
for(const [from,to] of redirects){if(!staticRoutes.some(r=>r.path===to))throw new Error('Missing redirect target '+to);}
await fs.writeFile('content/redirects.json',JSON.stringify(redirects)+'\n');await fs.writeFile(root+'/_redirects',redirects.map(([a,b])=>`${a} ${b} 301`).join('\n')+'\n');
await fs.mkdir('docs',{recursive:true});await fs.writeFile('docs/URL-MIGRATION.csv','old_url,new_url,status,reason\n'+redirects.filter(([a])=>!a.endsWith('/')).map(([a,b])=>`${ORIGIN+a},${ORIGIN+b},301,${a==='/2'?'Removed design variant':'Equivalent canonical destination'}`).join('\n')+'\n');
await fs.writeFile(root+'/_routes.json',JSON.stringify({version:1,include:['/api/posts','/api/posts/*','/blog','/blog/*','/sitemap.xml','/404'],exclude:[]})+'\n');
await fs.writeFile(root+'/_headers',`/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  Permissions-Policy: camera=(), microphone=(), geolocation=()\n/assets/*\n  Cache-Control: public, max-age=86400, stale-while-revalidate=604800\n/blog/*.md\n  Content-Type: text/markdown; charset=utf-8\n/ai.md\n  Content-Type: text/markdown; charset=utf-8\n/llms.txt\n  Content-Type: text/plain; charset=utf-8\n/llms-full.txt\n  Content-Type: text/plain; charset=utf-8\n`);
for(const file of (await walk(root)).filter(f=>f.endsWith('.css')||f.endsWith('.js'))){const result=await transform(await fs.readFile(file,'utf8'),{loader:file.endsWith('.css')?'css':'js',minify:true,target:'es2022'});await fs.writeFile(file,result.code);}
console.log(`Built ${staticRoutes.length} indexable pages, ${posts.length} articles, 18 comparison/alternative guides. Mode: ${production?'production':'preview (noindex)'}.`);
